services:
  backend:
    image: ammu1406/student-backend:latest
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

